### ISSUE TITLE
Add share buttons: slashdot, hackernews

### ISSUE THREAD

**Issue by selivan** [selivan/selivan.github.io#1]
HN: https://news.ycombinator.com/bookmarklet.html

**Comment by selivan** [comment]
LOR thread: https://www.linux.org.ru/forum/talks/12782946

**Comment by selivan** [comment]
Free social icons: https://www.iconfinder.com/iconsets/social-icons-33

Idea: black and white buttons.

**Comment by MiteshShah** [comment]
Code: https://github.com/MiteshShah/miteshshah.github.io/blob/master/_includes/_social-share.html

Website: https://miteshshah.github.io/

**Comment by selivan** [comment]
Get all possible share links in one place: https://www.addtoany.com/share

Get SVG icons: https://www.iconfinder.com/iconsets/social-icons-33

Done:
* Hacker news
* Linkedin
* Slashdot
