### ISSUE TITLE
Resume on personal page

### ISSUE THREAD

**Issue by selivan** [selivan/selivan.github.io#4]
Better that anywhere else on web, even than in google docs probably.
Or at least link to google docs.
And linkedin profile in resume.

? May be: selivan.github.io/cv - redirect to linkedin or somewhere else

**Comment by selivan** [comment]
Important: https://stackoverflow.com/jobs/cv/edit/163314 - may be useful

**Comment by MiteshShah** [comment]
https://miteshshah.github.io/resume/

**Comment by selivan** [comment]
Done: https://selivan.github.io/cv/
