### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by selivan** [selivan/selivan.github.io#6]
Tags:
- visible in posts
- visible in posts list
- separate tag list

Good idea:
http://pavdmyt.com/how-to-implement-tags-at-jekyll-website/

**Comment by MiteshShah** [comment]
https://miteshshah.github.io/tag/

**Comment by selivan** [comment]
Solved some time ago with http://pavdmyt.com/how-to-implement-tags-at-jekyll-website/
@MiteshShah , thanks for the example.
